keep_lane:
  path: "ffstreams/auto_driving/keep_lane/"
  gif_path: "ffstreams/auto_driving/gifs/keep_lane_gifs/"

lane_change:
  path : "ffstreams/auto_driving/lane_change/"
  gif_path: "ffstreams/auto_driving/gifs/lane_change_gifs/"

commonroad:
  path: "ffstreams/auto_driving/commonroad/"
  gif_path: "ffstreams/auto_driving/gifs/commonroad_gifs/" 

cr_scene:
  #path: "datasets/commonroad/CHN_Tianjin-12_28_T-1.xml"
  #path: "datasets/commonroad/USA_US101-1_1_T-1.xml"     #change_scenario
  #path: "datasets/commonroad/DEU_Nuremberg-39_5_T-1.xml"  
  path: "datasets/commonroad/USA_US101-22_3_T-1.xml"
  #path: "datasets/commonroad/DEU_Nuremberg-35_1_T-1.xml"
  #path: "datasets/commonroad/ITA_Empoli-18_1_T-1.xml" # only 4 seconds

apollo:
  path: "ffstreams/auto_driving/apollo/"

prediction_visualization:
  visualize: True